name: cli-skel
channels:
  - conda-forge
dependencies:
  - conda-forge::python >= 3.12
  - conda-forge::pip
  - setuptools >= 61.0
  - setuptools-scm >= 8.0
  - pytest
  - pytest-cov
  - jupyter
  - myst-nb
  - sphinx-autoapi
  - sphinx-rtd-theme
  - sphinx-markdown-builder
  - tomlkit
